@startuml
'https://plantuml.com/class-diagram
header Bibliothek Klassendiagramm

class Person
class Buch
class Ausleihe {
    datum
}
class Reservation {
    datum
}

Person "1..1" -- "0..*" Ausleihe
Ausleihe "0..1" -- "1..1" Buch

Person "1..1" -- "0..*" Reservation
Reservation "0..*" -- "1..1" Buch

@enduml